# https://github.com/travis-ci/docs-travis-ci-com/issues/910
language: minimal
dist: trusty
sudo: required

env:
  # Matrix for testing against multiple OSes as needed in the future
  matrix:
    - OS_TYPE=centos OS_VERSION=7

services:
  - docker

before_install:
  - sudo apt-get update
  - openssl aes-256-cbc -K $encrypted_86d19777a929_key -iv $encrypted_86d19777a929_iv -in keys/id_rsa.enc -out keys/id_rsa -d
  - rm keys/id_rsa.enc
  - sudo docker pull centos:centos${OS_VERSION}
  - sudo docker build --no-cache --rm --file=docker/Dockerfile.centos-${OS_VERSION} -t puppettest .

script:
  # use this for Travis CI
  - sudo docker run puppettest
  # use this for local docker testing
  # - docker run --rm -it -e DEV_MODE=true

after_success:
  # - bash scripts/deploy.sh
