# https://github.com/travis-ci/docs-travis-ci-com/issues/910
language: minimal
dist: trusty
rvm:
  - 2.5.1
before_install:
  - bash scripts/install.sh
script:
  - echo 'Ready to deploy'
after_success:
  #- bash scripts/deploy.sh
  - echo 'pretend we deployed'
